# Generated by Django 3.1.7 on 2021-04-09 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(verbose_name='size')),
                ('full', models.CharField(max_length=1, verbose_name='full')),
                ('instructor', models.CharField(max_length=50, verbose_name='instructor')),
                ('gi', models.CharField(max_length=1, verbose_name='gi')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('participant_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='participant_id')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pages.classes')),
            ],
        ),
    ]
