# Generated by Django 3.1.7 on 2021-04-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name_plural': 'Participants'},
        ),
    ]
