# Generated by Django 3.1.7 on 2021-04-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_auto_20210409_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
