# Generated by Django 3.1.7 on 2021-04-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_auto_20210416_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='full',
        ),
    ]
