# Generated by Django 3.1.7 on 2021-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0006_remove_classes_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='num_signed_up',
            field=models.IntegerField(default=0, verbose_name='num_signed_up'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='size',
            field=models.IntegerField(default=10, verbose_name='size'),
        ),
    ]
