# Generated by Django 3.1.7 on 2021-04-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0012_auto_20210416_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='classes',
            name='time',
            field=models.TimeField(),
        ),
    ]
