# Generated by Django 3.1.7 on 2021-04-16 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0013_auto_20210416_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='time',
        ),
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
