# Generated by Django 3.2 on 2021-04-21 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0014_auto_20210416_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='time',
            field=models.CharField(choices=[('AM', '6:00 AM'), ('NOON', '12:00 PM'), ('PM', '7:00 PM')], default='AM', max_length=10, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='classes',
            name='gi',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='gi'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='type',
            field=models.CharField(choices=[('B', 'Adults - Basics'), ('A', 'Adults - Advanced'), ('C', 'Adults - Competition')], default='B', max_length=50, verbose_name='type'),
        ),
    ]
