# Generated by Django 3.2 on 2021-04-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0015_auto_20210421_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='class_id',
        ),
        migrations.AlterField(
            model_name='classes',
            name='gi',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='gi'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='time',
            field=models.CharField(choices=[('6:00 AM', '6:00 AM'), ('12:00 PM', '12:00 PM'), ('7:00 PM', '7:00 PM')], default='6:00 AM', max_length=10, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='type',
            field=models.CharField(choices=[('Basic', 'Adults - Basics'), ('Advanced', 'Adults - Advanced'), ('Competition', 'Adults - Competition')], default='Basic', max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='participant_id',
            field=models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='participant_id'),
        ),
    ]
