# Generated by Django 3.2 on 2021-04-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0017_participants_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='class_id',
        ),
    ]
