# Generated by Django 3.1.7 on 2021-04-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0020_alter_participants_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='type',
            field=models.CharField(choices=[('Adults - Basic', 'Adults - Basics'), ('Adults - Advanced', 'Adults - Advanced'), ('Adults - Competition', 'Adults - Competition'), ('Kids - Basic', 'Kids - Basic'), ('Kids - Advanced', 'Kids - Advanced'), ('Kids - Competition', 'Kids - Competition'), ('Open Mat', 'Open Mat')], default='Adults - Basic', max_length=50, verbose_name='type'),
        ),
    ]
